 ActiveSupport::Inflector.inflections(:en) do |inflect|

   inflect.irregular 'rol', 'roles'
   inflect.irregular 'cargo', 'cargos'
   inflect.irregular 'estado', 'estados'
   inflect.irregular 'nombre', 'nombres'
   inflect.irregular 'usuario', 'usuarios'
   inflect.irregular 'correo', 'correos'
   inflect.irregular 'user', 'users'
   inflect.irregular 'celular', 'celular'
   inflect.irregular 'cliente', 'clientes'
   inflect.irregular 'nit', 'nits'
   inflect.irregular 'nombre_contacto', 'nombres_contactos'
   inflect.irregular 'telefono', 'telefonos'
   inflect.irregular 'correo', 'correos'
   inflect.irregular 'direccion', 'direcciones'
   inflect.irregular 'contacto', 'contactos'

   inflect.irregular 'tamano', 'tamanos'
   inflect.irregular 'numero_pedido', 'numero_pedidos'
   inflect.irregular 'linea_de_impresion', 'lineas_de_impresiones'
   inflect.irregular 'tipo_de_linea', 'tipos_de_lineas'
   inflect.irregular 'tiempos_de_entrega', 'tiempos_de_entregas'
   inflect.irregular 'costo', 'costos'
   inflect.irregular 'fecha_compromiso', 'fechas_compromiso'
   inflect.irregular 'total_fechas_decompromiso','totales_fechas_decompromiso'

   inflect.irregular 'factura','facturas'
   inflect.irregular 'despacho', 'despachos'
   inflect.irregular 'lugar_a_factura','lugares_a_facturar'
   inflect.irregular 'recibe','reciben'

   inflect.irregular 'condicion_de_pedido','condiciones_de_pedido'
   inflect.irregular 'entregar_factura','entregar_facturas'

   inflect.irregular 'orden_de_produccion','ordenes_de_produccion'
   inflect.irregular 'fecha_final','fechas_finales'
   inflect.irregular 'fecha','fechas'
   inflect.irregular 'total','totales'
   inflect.irregular 'detalle_de_produccion','detalles_de_produccion'
   inflect.irregular 'inventario','inventarios'
   inflect.irregular 'numero_de_orden','numeros_de_ordenes'

   inflect.irregular 'codigo','codigos'
   inflect.irregular 'fecha','fechas'
   inflect.irregular 'cantidad','cantidades'

   inflect.irregular 'remision','remisiones'
   inflect.irregular 'fecha_de_despacho','fechas_de_despachos'
   inflect.irregular 'cantidad_enviada','cantidades_enviadas'
   inflect.irregular 'precio_a_facturar','precios_a_facturar'
   inflect.irregular 'cantidad_faltante','cantidades_faltantes'
   inflect.irregular 'anexo','anexos'
   inflect.irregular 'entrega_cumplida','entregas_cumplidas'

   inflect.irregular 'factura_despacho', 'facturas_despacho'
   inflect.irregular 'numero_de_factura', 'numeros_de_facturas'
   inflect.irregular 'cancelada', 'canceladas'
   inflect.irregular 'numero_de_remision', 'numeros_de_remisiones'
   inflect.irregular 'iva', 'ivas'
   inflect.irregular 'total_facturado', 'totales_facturados'
   inflect.irregular 'descuento', 'descuentos'

   inflect.irregular 'usuario_asignado', 'usuario_asignados'
   inflect.irregular 'habilitar_acabado', 'habilitar_acabados'
   inflect.irregular 'habilitar_impresion', 'habilitar_impresiones'
 end
