ActiveSupport::Inflector.inflections(:en) do |inflect|

  inflect.irregular 'rol', 'roles'
  inflect.irregular 'cargo', 'cargos'
  inflect.irregular 'estado', 'estados'
  inflect.irregular 'nombre', 'nombres'
  inflect.irregular 'usuario', 'usuarios'
  inflect.irregular 'correo', 'correos'
  inflect.irregular 'user', 'users'
  inflect.irregular 'celular', 'celular'
  inflect.irregular 'cliente', 'clientes'
  inflect.irregular 'nit', 'nits'
  inflect.irregular 'nombre_contacto', 'nombres_contactos'
  inflect.irregular 'telefono', 'telefonos'
  inflect.irregular 'correo', 'correos'
  inflect.irregular 'direccion', 'direcciones'
  inflect.irregular 'contacto', 'contactos'

  inflect.irregular 'tamano', 'tamanos'
  inflect.irregular 'numero_pedido', 'numero_pedidos'
  inflect.irregular 'linea_de_impresion', 'lineas_de_impresiones'
  inflect.irregular 'tipo_de_linea', 'tipos_de_lineas'
  inflect.irregular 'tiempos_de_entrega', 'tiempos_de_entregas'
  inflect.irregular 'costo', 'costos'
  inflect.irregular 'fecha_compromiso', 'fechas_compromiso'
  inflect.irregular 'total_fechas_decompromiso','totales_fechas_decompromiso'

  inflect.irregular 'factura','facturas'
  inflect.irregular 'despacho', 'despachos'
  inflect.irregular 'lugar_a_factura','lugares_a_facturar'
  inflect.irregular 'recibe','reciben'

  inflect.irregular 'condicion_de_pedido','condiciones_de_pedido'
  inflect.irregular 'entregar_factura','entregar_facturas'

  inflect.irregular 'orden_de_produccion','ordenes_de_produccion'
  inflect.irregular 'fecha_final','fechas_finales'
  inflect.irregular 'fecha','fechas'
  inflect.irregular 'total','totales'
  inflect.irregular 'detalle_de_produccion','detalles_de_produccion'
  inflect.irregular 'inventario','inventarios'
  inflect.irregular 'numero_de_orden','numeros_de_ordenes'

  inflect.irregular 'codigo','codigos'
  inflect.irregular 'fecha','fechas'
  inflect.irregular 'cantidad','cantidades'

  inflect.irregular 'remision','remisiones'
  inflect.irregular 'fecha_de_despacho','fechas_de_despachos'
  inflect.irregular 'cantidad_enviada','cantidades_enviadas'
  inflect.irregular 'precio_a_facturar','precios_a_facturar'
  inflect.irregular 'cantidad_faltante','cantidades_faltantes'
  inflect.irregular 'anexo','anexos'
  inflect.irregular 'entrega_cumplida','entregas_cumplidas'

  inflect.irregular 'factura_despacho', 'facturas_despacho'
  inflect.irregular 'numero_de_factura', 'numeros_de_facturas'
  inflect.irregular 'cancelada', 'canceladas'
  inflect.irregular 'numero_de_remision', 'numeros_de_remisiones'
  inflect.irregular 'iva', 'ivas'
  inflect.irregular 'total_facturado', 'totales_facturados'
  inflect.irregular 'descuento', 'descuentos'

  inflect.irregular 'usuario_asignado', 'usuario_asignados'
  inflect.irregular 'habilitar_acabado', 'habilitar_acabados'
  inflect.irregular 'habilitar_impresion', 'habilitar_impresiones'

  inflect.irregular 'dimension', 'dimensiones'
  inflect.irregular 'dimension_1', 'dimensiones_1'
  inflect.irregular 'dimension_2', 'dimensiones_2'
  inflect.irregular 'numero_de_montaje', 'numero_de_montajes'
  inflect.irregular 'tipo_de_unidad', 'tipo_de_unidades'
  inflect.irregular 'pieza', 'piezas'
  inflect.irregular 'maquina', 'maquinas'
  inflect.irregular 'linea_producto', 'lineas_productos'

  inflect.irregular 'pieza_a_decorar', 'piezas_a_decorar'
  inflect.irregular 'produccion_orden', 'producciones_ordenes'
  inflect.irregular 'montaje','montajes'
  inflect.irregular 'cantidad_programada', 'cantidades_programadas'
  inflect.irregular 'precio_unitario', 'precios_unitarios'
  inflect.irregular 'valor_total', 'valores_totales'
  inflect.irregular 'tipo_de_produccion', 'tipos_de_producciones'
  inflect.irregular 'tamanos_total', 'tamanos_totales'
  inflect.irregular 'cavidad', 'cavidades'
  inflect.irregular 'cantidad_hoja', 'cantidades_hojas'
  inflect.irregular 'retiro', 'retiros'
  inflect.irregular 'modo_de_empaque', 'modos_de_empaques'
  inflect.irregular 'fecha_de_creacion', 'fechas_de_creacion'
  inflect.irregular 'material', 'materiales'
  inflect.irregular 'temperatura', 'temperaturas'
  inflect.irregular 'orden_produccion', 'ordenes_produccion'
  inflect.irregular 'dia', 'dias'
  inflect.irregular 'mes', 'meses'
  inflect.irregular 'formato_op', 'formatos_op'
  inflect.irregular 'linea_de_color', 'lineas_de_colores'

  inflect.irregular 'malla', 'mallas'
  inflect.irregular 'tinta_fop_tiro', 'tintas_fop_tiro'
  inflect.irregular 'tinta_fop_retiro', 'tintas_fop_retiro'
  inflect.irregular 'tipo_de_tinta', 'tipos_de_tintas'
  inflect.irregular 'color', 'colores'
  inflect.irregular 'tinta', 'tintas'
  inflect.irregular 'formulado', 'formulados'

end
